name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Get credentials
        id: credentials
        run: |
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

      - name: Run Cypress tests
        run: npm run cypress:run
        env:
          USERNAME: ${{ env.USERNAME }}  
          PASSWORD: ${{ env.PASSWORD }}  

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/results
